#!/usr/bin/env python3
"""Proof 2 — an MCP client that discovers and uses the tools over stdio.

    python examples/agent_demo.py [--design ...] [--transcript artifacts/mcp_session.md]

It launches ``python -m soc_explorer.mcp_server`` as a subprocess and speaks
the real MCP protocol to it (initialize, tools/list, tools/call). No LLM and
no network, which the exercise explicitly allows — and which makes the demo
reproducible in front of a reviewer.

The *policy* is scripted, but the *decisions are not*: the agent reads the
missing id out of a validation issue, recovers from a NOT_FOUND using
``details.did_you_mean``, and fixes an argument error using the list of valid
check names the server returned. Nothing below hardcodes ``sram0``, ``L7`` or
a check name. That is the property worth demonstrating: the tools carry enough
structure for a caller to self-correct.

To avoid dirtying the committed fixture, the design is copied to a temporary
directory and the server is pointed at the copy, so the run can go all the way
through a persisted repair.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

import anyio
from mcp import ClientSession
from mcp.client.stdio import StdioServerParameters, stdio_client

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DESIGN = ROOT / "data" / "designs" / "orion_soc.json"
DEFAULT_TRANSCRIPT = ROOT / "artifacts" / "mcp_session.md"


class Transcript:
    """Collects the session as markdown, and echoes it live on stdout."""

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.calls = 0

    def head(self, text: str) -> None:
        self._emit(f"\n## {text}\n")

    def note(self, text: str) -> None:
        self._emit(text)

    def block(self, payload: Any, lang: str | None = None) -> None:
        is_text = isinstance(payload, str)
        body = payload if is_text else json.dumps(payload, indent=2, ensure_ascii=False)
        self._emit(f"```{lang or ('text' if is_text else 'json')}\n{body}\n```")

    def _emit(self, text: str) -> None:
        self.lines.append(text)
        print(text, flush=True)

    def render(self, header: dict[str, Any]) -> str:
        front = [
            "# MCP session transcript — soc-explorer",
            "",
            "Generated by `examples/agent_demo.py`: a real MCP client talking to",
            "`python -m soc_explorer.mcp_server` over stdio. No LLM, no network.",
            "",
        ]
        front += [f"- **{key}**: {value}" for key, value in header.items()]
        return "\n".join(front + self.lines) + "\n"


async def call(
    session: ClientSession,
    tx: Transcript,
    intent: str,
    tool: str,
    arguments: dict[str, Any],
    highlight: Callable[[Any], Any] | None = None,
) -> dict[str, Any]:
    """One MCP tools/call, recorded with the intent behind it."""
    tx.calls += 1
    tx.head(f"Step {tx.calls} — {intent}")
    tx.block({"tool": tool, "arguments": arguments})
    result = await session.call_tool(tool, arguments)
    envelope = result.structured_content
    assert isinstance(envelope, dict), "server must return structuredContent"
    tx.note(f"`isError={result.is_error}` · `ok={envelope['ok']}`")
    if highlight is not None:
        tx.block(highlight(envelope))
    elif envelope["ok"]:
        tx.block(envelope["result"])
    else:
        tx.block(envelope["error"])
    return envelope


async def run(design: Path, transcript_path: Path) -> int:
    tx = Transcript()
    workdir = Path(tempfile.mkdtemp(prefix="soc-explorer-demo-"))
    working_copy = workdir / design.name
    shutil.copy(design, working_copy)

    params = StdioServerParameters(
        command=sys.executable,
        args=["-m", "soc_explorer.mcp_server", "--design", str(working_copy)],
        cwd=str(ROOT),
    )

    async with stdio_client(params) as (read_stream, write_stream):
        async with ClientSession(read_stream, write_stream) as session:
            # --- discovery ------------------------------------------------
            init = await session.initialize()
            tx.head("Handshake")
            tx.block(
                {
                    "server": f"{init.server_info.name} {init.server_info.version}",
                    "protocol_version": str(init.protocol_version),
                    "instructions_excerpt": (init.instructions or "").splitlines()[0],
                }
            )

            listed = await session.list_tools()
            tx.head("Discovery — tools/list")
            tx.note(f"{len(listed.tools)} tools advertised; the host learns which ones write:")
            tx.block(
                [
                    {
                        "name": tool.name,
                        "readOnlyHint": bool(tool.annotations and tool.annotations.read_only_hint),
                        "required": sorted(tool.input_schema.get("required", [])),
                    }
                    for tool in listed.tools
                ]
            )

            # --- orientation ----------------------------------------------
            await call(
                session, tx, "Orient: what is this design?", "describe_design", {},
                lambda env: {
                    key: env["result"][key]
                    for key in ("name", "version", "component_count", "link_count",
                                "components_by_kind", "clock_domains", "checks_available")
                },
            )

            # --- an argument error the agent recovers from -----------------
            bad = await call(
                session, tx,
                "Validate — but with a guessed check name, on purpose",
                "validate_design", {"checks": ["bandwidth"]},
            )
            available = bad["error"]["details"]["available_checks"]
            tx.note(
                "The server did not just say *no*: it returned the valid check "
                f"names, so the agent can retry. Picked from the response: "
                f"`{available[0]}` … ({len(available)} available)."
            )

            # --- real validation ------------------------------------------
            verdict = await call(
                session, tx, "Validate for real, errors only",
                "validate_design", {"min_severity": "error"},
                lambda env: env["result"]["issues"],
            )
            errors = verdict["result"]["issues"]
            if not errors:
                tx.note("No error-severity issue; nothing to repair.")
                return _finish(tx, transcript_path, design, working_copy)

            dangling = next(
                (issue for issue in errors if issue["code"] == "DANGLING_LINK_ENDPOINT"), None
            )
            if dangling is None:
                tx.note("No dangling endpoint in this design; stopping after diagnosis.")
                return _finish(tx, transcript_path, design, working_copy)

            broken_link = dangling["element_id"]
            missing_id = dangling["details"]["missing_id"]
            role = dangling["details"]["role"]
            tx.note(
                f"Diagnosis read from the payload: link `{broken_link}` has "
                f"`{role}={missing_id}`, which is not a component."
            )

            # --- NOT_FOUND, then self-correction --------------------------
            miss = await call(
                session, tx,
                f"Look up {missing_id!r} — the id the broken link references",
                "get_component", {"component_id": missing_id},
            )
            suggestions = miss["error"]["details"].get("did_you_mean") or []
            if not suggestions:
                tx.note("No suggestion returned; the agent cannot self-correct here.")
                return _finish(tx, transcript_path, design, working_copy)
            target = suggestions[0]
            tx.note(f"`details.did_you_mean` proposes `{target}` — retrying with it.")

            await call(
                session, tx, f"Fetch the suggested component {target!r}",
                "get_component", {"component_id": target},
                lambda env: {
                    key: env["result"][key]
                    for key in ("id", "name", "kind", "link_count", "incoming_links", "outgoing_links")
                },
            )

            await call(
                session, tx,
                f"Confirm the impact: can an initiator even reach {target!r}?",
                "find_path", {"src": "cpu0", "dst": target},
            )

            # --- preview, then repair -------------------------------------
            preview = await call(
                session, tx,
                f"Preview the repair: point {broken_link}.{role} at {target!r} (persist=false)",
                "set_link_endpoint",
                {"link_id": broken_link, "role": role, "component_id": target},
                lambda env: {
                    "change": env["result"]["change"],
                    "dry_run": env["result"]["dry_run"],
                    "validation": {
                        "before": env["result"]["validation"]["before"],
                        "after": env["result"]["validation"]["after"],
                        "resolved_issues": [
                            (i["code"], i["element_id"])
                            for i in env["result"]["validation"]["resolved_issues"]
                        ],
                        "new_issues": [
                            (i["code"], i["element_id"])
                            for i in env["result"]["validation"]["new_issues"]
                        ],
                    },
                },
            )
            delta = preview["result"]["validation"]
            tx.note(
                f"The preview is decision-grade: {len(delta['resolved_issues'])} issue(s) "
                f"resolved, {len(delta['new_issues'])} created, file untouched "
                f"(`dry_run={preview['result']['dry_run']}`)."
            )

            await call(
                session, tx, "Prove nothing was written yet", "get_link",
                {"link_id": broken_link},
                lambda env: {key: env["result"][key] for key in ("id", "src", "dst", "dst_exists")},
            )

            await call(
                session, tx, "Apply it for real (persist=true)", "set_link_endpoint",
                {"link_id": broken_link, "role": role, "component_id": target, "persist": True},
                lambda env: {
                    "persisted": env["result"]["persisted"],
                    "backup_path": env["result"]["backup_path"],
                    "change": env["result"]["change"],
                },
            )

            await call(
                session, tx, "Re-validate: errors gone?", "validate_design",
                {"min_severity": "error"},
                lambda env: {"issue_count": env["result"]["issue_count"], "issues": env["result"]["issues"]},
            )

            await call(
                session, tx, f"And now cpu0 -> {target}?", "find_path",
                {"src": "cpu0", "dst": target},
                lambda env: {
                    "found": env["result"]["found"],
                    "hops": env["result"]["hops"],
                    "links": [link["id"] for link in env["result"]["links"]],
                    "bottleneck": env["result"]["bottleneck"],
                    "total_latency_ns": env["result"]["total_latency_ns"],
                },
            )

            await call(
                session, tx, "Hand a human-readable summary back", "export_report",
                {"format": "text"}, lambda env: env["result"],
            )

    return _finish(tx, transcript_path, design, working_copy)


def _finish(tx: Transcript, transcript_path: Path, design: Path, working_copy: Path) -> int:
    header = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "design (source)": design.relative_to(ROOT) if design.is_relative_to(ROOT) else design,
        "design (server worked on a throwaway copy)": working_copy,
        "transport": "stdio subprocess",
        "tool calls": tx.calls,
        "LLM used": "none — scripted policy, decisions read from tool responses",
    }
    transcript_path.parent.mkdir(parents=True, exist_ok=True)
    transcript_path.write_text(tx.render(header), encoding="utf-8")
    print(f"\n[demo] transcript written to {transcript_path}", flush=True)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--design", default=str(DEFAULT_DESIGN))
    parser.add_argument("--transcript", default=str(DEFAULT_TRANSCRIPT))
    args = parser.parse_args()
    return anyio.run(run, Path(args.design), Path(args.transcript))


if __name__ == "__main__":
    raise SystemExit(main())
